# Generated by Django 4.2.5 on 2023-09-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fears', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fearintensity',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='fearintensity',
            old_name='modified_at',
            new_name='modified',
        ),
    ]
