# Generated by Django 4.2.5 on 2023-09-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fears', '0002_rename_created_at_fearintensity_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fearintensity',
            old_name='modified',
            new_name='updated',
        ),
    ]
