# Generated by Django 4.2.5 on 2023-09-21 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_alter_patient_fears'),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTherapistConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPatientAccepting', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='patients.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='therapists.therapist')),
            ],
            options={
                'unique_together': {('therapist', 'patient')},
            },
        ),
    ]
