# Generated by Django 4.2.5 on 2023-09-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='slug',
        ),
    ]
